services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: db_agendamento
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "db_agendamento" ]
      interval: 10s
      timeout: 5s
      retries: 3

  api_service:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING.DATASOURCE.URL: jdbc:postgresql://postgres:5432/db_agendamento
      SPRING.DATASOURCE.USERNAME: postgres
      SPRING.DATASOURCE.PASSWORD: 123
    ports:
      - "8080:8080"

volumes:
  postgres_data: